pub static WORLD_SIZE: f64 = 1000.0;
pub static MAX_SPHERE_R: f64 = 250.0;
pub static FOOD_SPAWN_R_MIN: f64 = 1.0;
pub static FOOD_SPAWN_R_MAX: f64 = 5.0;
pub static AM_SPAWN_R_MIN: f64 = 1.0;
pub static AM_SPAWN_R_MAX: f64 = 20.0;
pub static STARTING_PLAYER_R: f64 = 5.0;
pub static STARTING_PLAYER_R_RANDOMNESS: f64 = 1.0;
pub static MAX_SPHERE_SPEED: f64 = 100.0;
pub static FOOD_SPAWN_DELAY: f64 = 0.1;
pub static AM_SPAWN_DELAY: f64 = 1.0;
pub static MAX_SPHERE_COUNT: usize = 1000;
pub static SPHERE_COLOR_MIN: u32 = 0x66;
pub static SPHERE_COLOR_MAX: u32 = 0xcc;
pub static R_DECREASE_RATIO: f64 = 0.001;

pub static SHOOT_DELAY: f64 = 0.1;
pub static SHOOT_AREA_RATIO_SQ: f64 = 0.98;
pub static SHOOT_AREA_RATIO: f64 = 0.98994949366;
pub static BULLET_AREA_RATIO: f64 = 0.14142135623;
pub static SHOOT_FORCE: f64 = 5.0;
pub static BULLET_SPEED: f64 = 120.0;

pub static FAKE_NAME_LEN: usize = 150;

pub static FAKE_PLAYER_NAMES: [&str; 150] = [
    "Bambino",
    "Stud",
    "Babe",
    "Tater Tot",
    "Coach",
    "Amazon",
    "Lady",
    "Ticklebutt",
    "Rockette",
    "Goose",
    "Einstein",
    "Sweetums",
    "Tater",
    "Dearey",
    "Frau Frau",
    "Friendo",
    "Apple Jack",
    "Brown Sugar",
    "Rosie",
    "Anvil",
    "Fun Size",
    "Cold Front",
    "Amiga",
    "Cinnamon",
    "Silly Sally",
    "Tickles",
    "Thunder Thighs",
    "Juicy",
    "Blimpie",
    "Double Bubble",
    "Big Nasty",
    "Dulce",
    "Diet Coke",
    "Lulu",
    "Gordo",
    "Catwoman",
    "Colonel",
    "Flyby",
    "Golden Graham",
    "Boo Bear",
    "Bello",
    "T-Dawg",
    "Piggy",
    "Gams",
    "Amour",
    "Wifey",
    "Goonie",
    "Chubs",
    "Inchworm",
    "Belch",
    "Terminator",
    "Boo Bug",
    "Donuts",
    "Hawk",
    "Figgy",
    "Pyscho",
    "Hulk",
    "Fellow",
    "Bug",
    "Diesel",
    "Biscuit",
    "Toots",
    "Scarlet",
    "Sweet Tea",
    "Butter",
    "Janitor",
    "Cheese",
    "Spicy",
    "Crumbles",
    "Sassafras",
    "Drake",
    "Chewbacca",
    "Smiley",
    "Snuggles",
    "Chump",
    "Boomhauer",
    "Peppermint",
    "Cello",
    "Chef",
    "Taco",
    "Cheeky",
    "Slick",
    "Kitty",
    "Happy",
    "Pansy",
    "Ghoulie",
    "Tank",
    "Sunny",
    "Tough Guy",
    "Psycho",
    "Frodo",
    "Cat",
    "Music Man",
    "Birdy",
    "Halfmast",
    "Twizzler",
    "Cruella",
    "Creep",
    "Dottie",
    "Bellbottoms",
    "Red Velvet",
    "Gingersnap",
    "DJ",
    "Sassy",
    "Hammer",
    "Pixie",
    "Tomcat",
    "Silly Gilly",
    "Rumplestiltskin",
    "Queen Bee",
    "Gummy Pop",
    "Mouse",
    "Beanpole",
    "Dilly Dally",
    "Mad Max",
    "Baby",
    "Candycane",
    "Doll",
    "Donut",
    "Harry Potter",
    "Beauty",
    "Beast",
    "Ginger",
    "Skunk",
    "Lover",
    "Smudge",
    "Oompa Loompa",
    "Kit-Kat",
    "Luna",
    "Salt",
    "Butternut",
    "Snoopy",
    "Guapo",
    "Twinkly",
    "Cookie",
    "Candy",
    "Bubbles",
    "Pickle",
    "Skinny Jeans",
    "Buds",
    "Swiss Miss",
    "Dirty Harry",
    "Cricket",
    "Bean",
    "Grease",
    "Duckling",
    "Mistress",
    "Baby Boo",
    "Superman",
    "Ice Queen",
];
